import React, { useState, useEffect } from "react";
import Test from "./Test";
import "./App.css";
import {
  LineChart,
  Line,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
} from "recharts";

// import axios from "axios";

function App() {
  // const [grades, setGrades] = useState(false);
  useEffect(() => {
    // //   fetch("http://localhost:5000/api", { mode: "no-cors" })
    // //     .then((res) => {
    // //       console.log(res.json());
    // //     })
    // //     .catch((e) => console.log(e));
    // fetch("http://localhost:5000/api", {
    //   method: "POST",
    //   mode: "no-cors",
    //   headers: { "Content-Type": "application/json" },
    // })
    //   .then((response) => {
    //     //do something with response
    //     return response.json();
    //   })
    //   .then((text) => {
    //     console.log("hi");
    //     console.log(text);
    //   })
    //   .catch((err) => {
    //     throw new Error(err);
    //   });
  }, []);

  //FOR POINTS BASED CLASS, NO WEIGHT
  const data = [
    {
      terms: [
        {
          termID: 509,
          termName: "Q1",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 1,
          isPrimary: true,
          startDate: "2021-08-18",
          endDate: "2021-10-15",
        },
        {
          termID: 510,
          termName: "Q2",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 2,
          isPrimary: true,
          startDate: "2021-10-18",
          endDate: "2021-12-22",
        },
        {
          termID: 511,
          termName: "Q3",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 3,
          isPrimary: true,
          startDate: "2022-01-10",
          endDate: "2022-03-17",
        },
        {
          termID: 512,
          termName: "Q4",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 4,
          isPrimary: true,
          startDate: "2022-03-21",
          endDate: "2022-06-06",
        },
      ],
      details: [
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 509,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713796,
            score: "B",
            percent: 84.75,
            progressScore: "B",
            progressPercent: 84.75,
            progressPointsEarned: 139.0,
            progressTotalPoints: 164.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-30028100",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [
            {
              groupID: 7410,
              name: "Homework",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 71932,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 71152,
                  termID: 509,
                  assignmentName: "Chapter Four Multiple Choice",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-16T06:59:00.000Z",
                  assignedDate: "2021-10-14T07:00:00.000Z",
                  modifiedDate: "2021-10-18T20:48:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "34",
                  scorePoints: "34.0",
                  scorePercentage: "100.0",
                  totalPoints: 34,
                  comments: "34",
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: true,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 54112,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 53505,
                  termID: 509,
                  assignmentName: "Chapter Three M/C",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-10-02T07:00:00.000Z",
                  modifiedDate: "2021-10-02T18:05:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "18",
                  scorePoints: "18.0",
                  scorePercentage: "90.0",
                  totalPoints: 20,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 57069,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 56390,
                  termID: 509,
                  assignmentName: "Chapter Two Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-10-04T07:00:00.000Z",
                  modifiedDate: "2021-10-16T19:35:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "18",
                  scorePoints: "18.0",
                  scorePercentage: "72.0",
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37084,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36598,
                  termID: 509,
                  assignmentName: "Chapter One Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-22T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 24197,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 23769,
                  termID: 509,
                  assignmentName: "Class work",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-17T23:00:00.000Z",
                  assignedDate: "2021-09-08T07:00:00.000Z",
                  modifiedDate: "2021-09-17T23:54:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 15558,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 15301,
                  termID: 509,
                  assignmentName: "Chapter 1 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-01T06:59:00.000Z",
                  assignedDate: "2021-08-31T07:00:00.000Z",
                  modifiedDate: "2021-09-05T19:01:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "24",
                  scorePoints: "24.0",
                  scorePercentage: "80.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 181688,
                scoreID: 713796,
                groupID: 7410,
                progressScore: "B+",
                progressPercent: 87.39,
                progressTrendVal: null,
                progressPointsEarned: 104.0,
                progressTotalPoints: 119.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 7497,
              name: "Tests",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 59214,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 58520,
                  termID: 509,
                  assignmentName: "Chapter Two Essay",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-07T06:59:00.000Z",
                  assignedDate: "2021-10-06T07:00:00.000Z",
                  modifiedDate: "2021-10-06T19:54:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "21",
                  scorePoints: "21.0",
                  scorePercentage: "84.0",
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 32672,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 32274,
                  termID: 509,
                  assignmentName: "Chapter Three Essay",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-17T18:00:00.000Z",
                  assignedDate: "2021-09-15T07:00:00.000Z",
                  modifiedDate: "2021-10-06T18:42:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "14",
                  scorePoints: "14.0",
                  scorePercentage: "70.0",
                  totalPoints: 20,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 326303,
                scoreID: 713796,
                groupID: 7497,
                progressScore: "C+",
                progressPercent: 77.77,
                progressTrendVal: null,
                progressPointsEarned: 35.0,
                progressTotalPoints: 45.0,
                termID: 509,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 509,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            scoreID: 778243,
            score: "B-",
            percent: 80.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1829391107",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 1,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713798,
            progressScore: "B-",
            progressPercent: 81.53,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "1499993557",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21222,
              courseName: "AP Hum Geo",
              sectionID: 71637,
              taskID: 2,
              termID: 510,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 1,
              cumulativeTermName: "Q1",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: false,
              usePercent: false,
              curveID: 6,
              scoreID: 713797,
              progressScore: "B-",
              progressPercent: 81.53,
              progressPointsEarned: 234.0,
              progressTotalPoints: 287.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "1173892846",
              termName: "Q2",
              termSeq: 2,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 510,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713797,
            progressScore: "B-",
            progressPercent: 81.53,
            progressPointsEarned: 234.0,
            progressTotalPoints: 287.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "1173892846",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [
            {
              groupID: 7410,
              name: "Homework",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 117002,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 115968,
                  termID: 510,
                  assignmentName: "Chapter 7 Essays",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-30T07:59:00.000Z",
                  assignedDate: "2021-11-29T08:00:00.000Z",
                  modifiedDate: "2021-11-29T15:40:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "12",
                  scorePoints: "12.0",
                  scorePercentage: "30.0",
                  totalPoints: 40,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101167,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100239,
                  termID: 510,
                  assignmentName: "Chapter 7 Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-20T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101159,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100231,
                  termID: 510,
                  assignmentName: "Chapter 7 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-19T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-18T16:31:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "30",
                  scorePoints: "30.0",
                  scorePercentage: "100.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101156,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100228,
                  termID: 510,
                  assignmentName: "Chapter 6 Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-10T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 181689,
                scoreID: 713797,
                groupID: 7410,
                progressScore: "C+",
                progressPercent: 77.24,
                progressTrendVal: null,
                progressPointsEarned: 146.0,
                progressTotalPoints: 189.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 7497,
              name: "Tests",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 101153,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100225,
                  termID: 510,
                  assignmentName: "Chapter 6 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-10T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-11T18:29:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "30",
                  scorePoints: "30.0",
                  scorePercentage: "100.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 89190,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 88310,
                  termID: 510,
                  assignmentName: "Chapter 5 test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-30T06:59:00.000Z",
                  assignedDate: "2021-10-29T07:00:00.000Z",
                  modifiedDate: "2021-10-29T14:36:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "23",
                  scorePoints: "23.0",
                  scorePercentage: "100.0",
                  totalPoints: 23,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 326304,
                scoreID: 713797,
                groupID: 7497,
                progressScore: "B+",
                progressPercent: 89.79,
                progressTrendVal: null,
                progressPointsEarned: 88.0,
                progressTotalPoints: 98.0,
                termID: 510,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1395353462",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "2067476348",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-681855881",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 1,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-871948916",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21222,
              courseName: "AP Hum Geo",
              sectionID: 71637,
              taskID: 2,
              termID: 512,
              hasAssignments: false,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 3,
              cumulativeTermName: "Q3",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: false,
              usePercent: false,
              curveID: 6,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: false,
              _model: "PortalGradingTaskModel",
              _hashCode: "-1308748418",
              termName: "Q4",
              termSeq: 4,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1308748418",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1535902072",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
      ],
    },
  ];

  var dates = [];
  for (var tasks = 0; tasks < data[0].details.length; tasks++) {
    const groups = data[0].details[tasks].categories;

    if (groups.length > 0) {
      for (var i = 0; i < groups.length; i++) {
        var asgn = groups[i].assignments;
        for (var z = 0; z < asgn.length; z++) {
          var d = new Date(asgn[z].dueDate.split("T")[0]);
          if (asgn[z].score != null) {
            dates.push({
              date: d,
              score: Number(asgn[z].score),
              total: asgn[z].totalPoints,
              asgn: asgn[z].assignmentName,
            });
          }
        }
      }
    }
  }

  dates.sort(function (a, b) {
    return +new Date(a.date) - +new Date(b.date);
  });

  const HuGeo = [];
  let total = 0;
  let points = 0;
  for (var i = 0; i < dates.length; i++) {
    var grade = 0;
    points += dates[i].score;
    total += dates[i].total;
    grade = (points / total) * 100;

    HuGeo.push({
      date: dates[i].date.toLocaleDateString(),
      grade: grade.toFixed(2),
      name: dates[i].asgn,
    });
  }

  return (
    <div className="App">
      <LineChart width={600} height={300} data={HuGeo}>
        <Line type="monotone" dataKey="grade" stroke="#8884d8" />
        <Line type="monotone" dataKey="name" stroke="#8884d8" />
        <CartesianGrid stroke="#ccc" />
        <XAxis dataKey="date" />
        <YAxis />
        <Tooltip />
      </LineChart>
      <Test />
    </div>
  );
}

export default App;
