import React, { useState, useEffect } from "react";
import "./App.css";
import Paper from "@material-ui/core/Paper";
import {
  ArgumentAxis,
  ValueAxis,
  Chart,
  LineSeries,
} from "@devexpress/dx-react-chart-material-ui";
import { alpha } from "@material-ui/core/styles";
function App() {
  const [grades, setGrades] = useState(false);
  useEffect(() => {
    // fetch(
    //   "https://fremontunifiedca.infinitecampus.org/campus/resources/portal/grades",
    //   {
    //     headers: {
    //       // Connection: "keep-alive",
    //       // "sec-ch-ua":
    //       // '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
    //       Accept: "application/json, text/plain, */*",
    //       // Expires: "0",
    //       // "Cache-Control": "no-cache",
    //       // "sec-ch-ua-mobile": "?0",
    //       // "User-Agent":
    //       // "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
    //       // "sec-ch-ua-platform": '"Windows"',
    //       // "Sec-Fetch-Site": "same-origin",
    //       // "Sec-Fetch-Mode": "cors",
    //       // "Sec-Fetch-Dest": "empty",
    //       Referer:
    //         "https://fremontunifiedca.infinitecampus.org/campus/apps/portal/student/grades",
    //       "Accept-Language": "en-US,en;q=0.9,es;q=0.8",
    //       Cookie:
    //         "_did-603548799=08c09554-c053-4c8f-b905-ffb653761f27; JSESSIONID=EDC353307CC7DA05E3430E7F4AE8DFDD; XSRF-TOKEN=1a0bb64c-ed3f-41f9-8afa-7a735a96056e; tool=; selection=; portalApp=student; portalLang=en; appName=fremont; sis-cookie=!xP52pFe5WYJWPfIuK9LQTj293o8cRjnpFsYVLIm6v9YtOqLRETtsrNt9GeIQgWUOaovI05QpDoHqXes=",
    //     },
    //   }
    // )
    //   .then((res) => res.json())
    //   .then((json) => setGrades(json));
  }, []);

  //FOR POINTS BASED CLASS, NO WEIGHT
  const data = [
    {
      terms: [
        {
          termID: 509,
          termName: "Q1",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 1,
          isPrimary: true,
          startDate: "2021-08-18",
          endDate: "2021-10-15",
        },
        {
          termID: 510,
          termName: "Q2",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 2,
          isPrimary: true,
          startDate: "2021-10-18",
          endDate: "2021-12-22",
        },
        {
          termID: 511,
          termName: "Q3",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 3,
          isPrimary: true,
          startDate: "2022-01-10",
          endDate: "2022-03-17",
        },
        {
          termID: 512,
          termName: "Q4",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 4,
          isPrimary: true,
          startDate: "2022-03-21",
          endDate: "2022-06-06",
        },
      ],
      details: [
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 509,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713796,
            score: "B",
            percent: 84.75,
            progressScore: "B",
            progressPercent: 84.75,
            progressPointsEarned: 139.0,
            progressTotalPoints: 164.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-30028100",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [
            {
              groupID: 7410,
              name: "Homework",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 71932,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 71152,
                  termID: 509,
                  assignmentName: "Chapter Four Multiple Choice",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-16T06:59:00.000Z",
                  assignedDate: "2021-10-14T07:00:00.000Z",
                  modifiedDate: "2021-10-18T20:48:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "34",
                  scorePoints: "34.0",
                  scorePercentage: "100.0",
                  totalPoints: 34,
                  comments: "34",
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: true,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 54112,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 53505,
                  termID: 509,
                  assignmentName: "Chapter Three M/C",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-10-02T07:00:00.000Z",
                  modifiedDate: "2021-10-02T18:05:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "18",
                  scorePoints: "18.0",
                  scorePercentage: "90.0",
                  totalPoints: 20,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 57069,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 56390,
                  termID: 509,
                  assignmentName: "Chapter Two Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-10-04T07:00:00.000Z",
                  modifiedDate: "2021-10-16T19:35:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "18",
                  scorePoints: "18.0",
                  scorePercentage: "72.0",
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37084,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36598,
                  termID: 509,
                  assignmentName: "Chapter One Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-22T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 24197,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 23769,
                  termID: 509,
                  assignmentName: "Class work",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-17T23:00:00.000Z",
                  assignedDate: "2021-09-08T07:00:00.000Z",
                  modifiedDate: "2021-09-17T23:54:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 15558,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 15301,
                  termID: 509,
                  assignmentName: "Chapter 1 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-01T06:59:00.000Z",
                  assignedDate: "2021-08-31T07:00:00.000Z",
                  modifiedDate: "2021-09-05T19:01:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "24",
                  scorePoints: "24.0",
                  scorePercentage: "80.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 181688,
                scoreID: 713796,
                groupID: 7410,
                progressScore: "B+",
                progressPercent: 87.39,
                progressTrendVal: null,
                progressPointsEarned: 104.0,
                progressTotalPoints: 119.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 7497,
              name: "Tests",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 59214,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 58520,
                  termID: 509,
                  assignmentName: "Chapter Two Essay",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-07T06:59:00.000Z",
                  assignedDate: "2021-10-06T07:00:00.000Z",
                  modifiedDate: "2021-10-06T19:54:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "21",
                  scorePoints: "21.0",
                  scorePercentage: "84.0",
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 32672,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 32274,
                  termID: 509,
                  assignmentName: "Chapter Three Essay",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-09-17T18:00:00.000Z",
                  assignedDate: "2021-09-15T07:00:00.000Z",
                  modifiedDate: "2021-10-06T18:42:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "14",
                  scorePoints: "14.0",
                  scorePercentage: "70.0",
                  totalPoints: 20,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 326303,
                scoreID: 713796,
                groupID: 7497,
                progressScore: "C+",
                progressPercent: 77.77,
                progressTrendVal: null,
                progressPointsEarned: 35.0,
                progressTotalPoints: 45.0,
                termID: 509,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 509,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            scoreID: 778243,
            score: "B-",
            percent: 80.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1829391107",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 1,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713798,
            progressScore: "B+",
            progressPercent: 89.87,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "508994284",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21222,
              courseName: "AP Hum Geo",
              sectionID: 71637,
              taskID: 2,
              termID: 510,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 1,
              cumulativeTermName: "Q1",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: false,
              usePercent: false,
              curveID: 6,
              scoreID: 713797,
              progressScore: "B+",
              progressPercent: 89.87,
              progressPointsEarned: 222.0,
              progressTotalPoints: 247.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "193149957",
              termName: "Q2",
              termSeq: 2,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 510,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 713797,
            progressScore: "B+",
            progressPercent: 89.87,
            progressPointsEarned: 222.0,
            progressTotalPoints: 247.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "193149957",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [
            {
              groupID: 7410,
              name: "Homework",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 101167,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100239,
                  termID: 510,
                  assignmentName: "Chapter 7 Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-20T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101159,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100231,
                  termID: 510,
                  assignmentName: "Chapter 7 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-19T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-18T16:31:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "30",
                  scorePoints: "30.0",
                  scorePercentage: "100.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101156,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100228,
                  termID: 510,
                  assignmentName: "Chapter 6 Optional Homework",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-10T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 25,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 181689,
                scoreID: 713797,
                groupID: 7410,
                progressScore: "B+",
                progressPercent: 89.93,
                progressTrendVal: null,
                progressPointsEarned: 134.0,
                progressTotalPoints: 149.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 7497,
              name: "Tests",
              weight: 0.0,
              seq: 0,
              isExcluded: false,
              isWeighted: false,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 101153,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100225,
                  termID: 510,
                  assignmentName: "Chapter 6 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-11-10T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-11T18:29:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "30",
                  scorePoints: "30.0",
                  scorePercentage: "100.0",
                  totalPoints: 30,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 89190,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 88310,
                  termID: 510,
                  assignmentName: "Chapter 5 test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71637,
                  courseID: 21222,
                  dueDate: "2021-10-30T06:59:00.000Z",
                  assignedDate: "2021-10-29T07:00:00.000Z",
                  modifiedDate: "2021-10-29T14:36:00.000Z",
                  courseName: "AP Hum Geo",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "23",
                  scorePoints: "23.0",
                  scorePercentage: "100.0",
                  totalPoints: 23,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 326304,
                scoreID: 713797,
                groupID: 7497,
                progressScore: "B+",
                progressPercent: 89.79,
                progressTrendVal: null,
                progressPointsEarned: 88.0,
                progressTotalPoints: 98.0,
                termID: 510,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1395353462",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "2067476348",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-681855881",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 1,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-871948916",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21222,
              courseName: "AP Hum Geo",
              sectionID: 71637,
              taskID: 2,
              termID: 512,
              hasAssignments: false,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 3,
              cumulativeTermName: "Q3",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: false,
              usePercent: false,
              curveID: 6,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: false,
              _model: "PortalGradingTaskModel",
              _hashCode: "-1308748418",
              termName: "Q4",
              termSeq: 4,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 2,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1308748418",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21222,
            courseName: "AP Hum Geo",
            sectionID: 71637,
            taskID: 3,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1535902072",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
      ],
    },
  ];

  var dates = [];
  for (var tasks = 0; tasks < data[0].details.length; tasks++) {
    const groups = data[0].details[tasks].categories;

    if (groups.length > 0) {
      for (var i = 0; i < groups.length; i++) {
        var asgn = groups[i].assignments;
        for (var z = 0; z < asgn.length; z++) {
          var d = new Date(asgn[z].dueDate.split("T")[0]);

          dates.push({
            date: d,
            score: asgn[z].score,
            total: asgn[z].totalPoints,
          });
        }
      }
    }
  }

  dates.sort(function (a, b) {
    return +new Date(a.date) - +new Date(b.date);
  });
  // console.log(dates);

  const graph = [];
  let total = 0;
  let points = 0;
  for (var i = 0; i < dates.length; i++) {
    if (dates[i].score != null) {
      points += Number(dates[i].score);
      total += dates[i].total;
    }

    var grade = points / total;

    graph.push({ arg: dates[i].date.toLocaleDateString(), val: grade });
  }

  console.log("total " + total);
  console.log("points " + points);

  console.log(graph);

  // const datas = [
  //   { argument: 1, value: 10 },
  //   { argument: 2, value: 20 },
  //   { argument: 3, value: 30 },
  // ];

  return (
    <div className="App">
      <Paper>
        <Chart data={graph}>
          <ArgumentAxis />
          <ValueAxis />

          <LineSeries valueField="val" argumentField="arg" />
        </Chart>
      </Paper>
    </div>
  );
}

export default App;
