import React, { useState, useEffect, useRef, useMemo } from "react";
import {
  DataGrid,
  GridCellEditCommitParams,
  GridCellParams,
  GridColDef,
  GridRowModel,
  GridSortModel,
} from "@mui/x-data-grid";
import {
  LineChart,
  Line,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
} from "recharts";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";
import Box from "@mui/material/Box";
import PointsBased from "./PointsBased";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import InputLabel from "@mui/material/InputLabel";
import FormControl from "@mui/material/FormControl";

import "./App.css";

function Courses() {
  const data = [
    {
      terms: [
        {
          termID: 509,
          termName: "Q1",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 1,
          isPrimary: true,
          startDate: "2021-08-18",
          endDate: "2021-10-15",
        },
        {
          termID: 510,
          termName: "Q2",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 2,
          isPrimary: true,
          startDate: "2021-10-18",
          endDate: "2021-12-22",
        },
        {
          termID: 511,
          termName: "Q3",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 3,
          isPrimary: true,
          startDate: "2022-01-10",
          endDate: "2022-03-17",
        },
        {
          termID: 512,
          termName: "Q4",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 4,
          isPrimary: true,
          startDate: "2022-03-21",
          endDate: "2022-06-06",
        },
      ],
      details: [
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 509,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 740350,
            score: "A-",
            percent: 92.8,
            progressScore: "A",
            progressPercent: 93.7,
            progressPointsEarned: 321.0,
            progressTotalPoints: 330.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1075816885",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 80153,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79353,
                  termID: 509,
                  assignmentName: "3.11",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-16T06:59:00.000Z",
                  assignedDate: "2021-10-14T07:00:00.000Z",
                  modifiedDate: "2021-10-21T22:43:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 59109,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 58415,
                  termID: 509,
                  assignmentName: "Implicit Differentiation Worksheet",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-08T06:59:00.000Z",
                  assignedDate: "2021-10-06T07:00:00.000Z",
                  modifiedDate: "2021-10-14T19:34:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 57549,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 56866,
                  termID: 509,
                  assignmentName: "3.10",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-06T06:59:00.000Z",
                  assignedDate: "2021-10-05T07:00:00.000Z",
                  modifiedDate: "2021-10-14T18:37:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 55807,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 55189,
                  termID: 509,
                  assignmentName: "3.9",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-09-29T07:00:00.000Z",
                  modifiedDate: "2021-10-14T18:37:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 48390,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 47853,
                  termID: 509,
                  assignmentName: "3.7",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-30T06:59:00.000Z",
                  assignedDate: "2021-09-27T07:00:00.000Z",
                  modifiedDate: "2021-10-04T16:24:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 51524,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 50948,
                  termID: 509,
                  assignmentName: "3.8",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-30T06:59:00.000Z",
                  assignedDate: "2021-09-29T07:00:00.000Z",
                  modifiedDate: "2021-10-04T21:35:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 44469,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 43951,
                  termID: 509,
                  assignmentName: "3.6",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-25T06:59:00.000Z",
                  assignedDate: "2021-09-24T07:00:00.000Z",
                  modifiedDate: "2021-09-28T15:57:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 44464,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 43946,
                  termID: 509,
                  assignmentName: "3.5",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-24T06:59:00.000Z",
                  assignedDate: "2021-09-23T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37229,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36743,
                  termID: 509,
                  assignmentName: "3.4",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-21T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37217,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36731,
                  termID: 509,
                  assignmentName: "3.1",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-19T21:29:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37223,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36737,
                  termID: 509,
                  assignmentName: "3.1/3.2 Extra Practice",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37220,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36734,
                  termID: 509,
                  assignmentName: "3.2",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37226,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36740,
                  termID: 509,
                  assignmentName: "3.3",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 26378,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 25946,
                  termID: 509,
                  assignmentName: "Ch 1&2 HW",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-11T06:59:00.000Z",
                  assignedDate: "2021-09-10T07:00:00.000Z",
                  modifiedDate: "2021-09-11T01:01:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "100",
                  scorePoints: "100.0",
                  scorePercentage: "100.0",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244945,
                scoreID: 740350,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 230.0,
                progressTotalPoints: 230.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 13844,
              name: "Tests/Projects/Finals",
              weight: 70.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 26382,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 25950,
                  termID: 509,
                  assignmentName: "Ch 2 Test",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-09-11T06:59:00.000Z",
                  assignedDate: "2021-09-10T07:00:00.000Z",
                  modifiedDate: "2021-09-21T01:33:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "91",
                  scorePoints: "91.0",
                  scorePercentage: "91.0",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244946,
                scoreID: 740350,
                groupID: 13844,
                progressScore: "A-",
                progressPercent: 91.0,
                progressTrendVal: null,
                progressPointsEarned: 91.0,
                progressTotalPoints: 100.0,
                termID: 509,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 509,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 849964,
            score: "A",
            percent: 96.53,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "272236671",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 1,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 740352,
            score: "A",
            percent: 94.01,
            progressScore: "A",
            progressPercent: 94.01,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "1880225313",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21005,
              courseName: "AP Calc AB",
              sectionID: 71392,
              taskID: 2,
              termID: 510,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 1,
              cumulativeTermName: "Q1",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              scoreID: 740351,
              progressScore: "A",
              progressPercent: 94.01,
              progressPointsEarned: 633.5,
              progressTotalPoints: 660.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "954947826",
              termName: "Q2",
              termSeq: 2,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 510,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 740351,
            progressScore: "A",
            progressPercent: 94.01,
            progressPointsEarned: 633.5,
            progressTotalPoints: 660.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "954947826",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 131318,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 130233,
                  termID: 510,
                  assignmentName: "4.9 - 2",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-14T07:59:00.000Z",
                  assignedDate: "2021-12-10T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:42:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 131307,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 130222,
                  termID: 510,
                  assignmentName: "5.3",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-14T07:59:00.000Z",
                  assignedDate: "2021-12-10T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:42:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 125568,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 124512,
                  termID: 510,
                  assignmentName: "5.2",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-09T07:59:00.000Z",
                  assignedDate: "2021-12-06T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:42:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 119612,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 118562,
                  termID: 510,
                  assignmentName: "5.1",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-07T07:59:00.000Z",
                  assignedDate: "2021-11-30T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:36:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 110937,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 109951,
                  termID: 510,
                  assignmentName: "4.9",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-19T07:59:00.000Z",
                  assignedDate: "2021-11-17T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:36:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 108442,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 107461,
                  termID: 510,
                  assignmentName: "4.7",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-18T07:59:00.000Z",
                  assignedDate: "2021-11-15T08:00:00.000Z",
                  modifiedDate: "2021-12-20T04:36:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 108436,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 107455,
                  termID: 510,
                  assignmentName: "4.6",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-17T07:59:00.000Z",
                  assignedDate: "2021-11-12T08:00:00.000Z",
                  modifiedDate: "2021-11-19T17:13:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101308,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100380,
                  termID: 510,
                  assignmentName: "4.5 ",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-12T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-17T20:28:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 100604,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 99680,
                  termID: 510,
                  assignmentName: "4.4",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-09T07:59:00.000Z",
                  assignedDate: "2021-11-08T08:00:00.000Z",
                  modifiedDate: "2021-11-17T20:26:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 84135,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 83312,
                  termID: 510,
                  assignmentName: "4.3 ",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-29T06:59:00.000Z",
                  assignedDate: "2021-10-25T07:00:00.000Z",
                  modifiedDate: "2021-11-17T20:22:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 80107,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79307,
                  termID: 510,
                  assignmentName: "4.2",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-22T06:59:00.000Z",
                  assignedDate: "2021-10-21T07:00:00.000Z",
                  modifiedDate: "2021-10-22T19:13:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 80318,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79518,
                  termID: 510,
                  assignmentName: "4.1",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-10-20T06:59:00.000Z",
                  assignedDate: "2021-10-18T07:00:00.000Z",
                  modifiedDate: "2021-10-22T19:13:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244947,
                scoreID: 740351,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 350.0,
                progressTotalPoints: 350.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 13844,
              name: "Tests/Projects/Finals",
              weight: 70.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 141039,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 139956,
                  termID: 510,
                  assignmentName: "Final Exam",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-20T07:59:00.000Z",
                  assignedDate: "2021-12-19T08:00:00.000Z",
                  modifiedDate: "2021-12-22T23:01:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "95",
                  scorePoints: "95.0",
                  scorePercentage: "95.0",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 142688,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 141600,
                  termID: 510,
                  assignmentName: "Ch 4 Test",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-18T07:59:00.000Z",
                  assignedDate: "2021-12-13T08:00:00.000Z",
                  modifiedDate: "2021-12-23T22:18:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 123342,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 122289,
                  termID: 510,
                  assignmentName: "Cheat Sheet Extra Credit",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-12-07T07:59:00.000Z",
                  assignedDate: "2021-12-03T08:00:00.000Z",
                  modifiedDate: "2021-12-22T06:36:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 100661,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 99737,
                  termID: 510,
                  assignmentName: "Ch 3 Test",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2021-11-09T07:59:00.000Z",
                  assignedDate: "2021-11-08T08:00:00.000Z",
                  modifiedDate: "2021-11-09T04:28:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "87.5",
                  scorePoints: "87.5",
                  scorePercentage: "87.5",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244948,
                scoreID: 740351,
                groupID: 13844,
                progressScore: "A-",
                progressPercent: 91.45,
                progressTrendVal: null,
                progressPointsEarned: 283.5,
                progressTotalPoints: 310.0,
                termID: 510,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 988036,
            score: "A-",
            percent: 92.47,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-610888853",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 511,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 1076674,
            progressScore: "A",
            progressPercent: 100.0,
            progressPointsEarned: 40.0,
            progressTotalPoints: 40.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1790590159",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 177539,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 176193,
                  termID: 511,
                  assignmentName: "6.4",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-02-10T07:59:00.000Z",
                  assignedDate: "2022-02-09T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 172385,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 171047,
                  termID: 511,
                  assignmentName: "6.3",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-02-04T07:59:00.000Z",
                  assignedDate: "2022-02-02T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 169562,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 168234,
                  termID: 511,
                  assignmentName: "6.2",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-02-02T07:59:00.000Z",
                  assignedDate: "2022-01-31T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 165040,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 163773,
                  termID: 511,
                  assignmentName: "6.1",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-01-28T07:59:00.000Z",
                  assignedDate: "2022-01-26T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 156850,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 155657,
                  termID: 511,
                  assignmentName: "5.7",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-01-22T07:59:00.000Z",
                  assignedDate: "2022-01-20T08:00:00.000Z",
                  modifiedDate: "2022-01-31T17:38:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 169583,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 168255,
                  termID: 511,
                  assignmentName: "5.6",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-01-21T07:59:00.000Z",
                  assignedDate: "2022-01-20T08:00:00.000Z",
                  modifiedDate: "2022-01-31T17:38:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 150841,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 149678,
                  termID: 511,
                  assignmentName: "5.5",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-01-15T07:59:00.000Z",
                  assignedDate: "2022-01-13T08:00:00.000Z",
                  modifiedDate: "2022-01-18T19:20:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 148269,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 147123,
                  termID: 511,
                  assignmentName: "5.4",
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  dueDate: "2022-01-13T07:59:00.000Z",
                  assignedDate: "2022-01-11T08:00:00.000Z",
                  modifiedDate: "2022-01-18T19:20:00.000Z",
                  courseName: "AP Calc AB",
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  isValidRubric: false,
                  isValidMark: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 616191,
                scoreID: 1076674,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 40.0,
                progressTotalPoints: 40.0,
                termID: 511,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1542803576",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 1,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 1076676,
            progressScore: "A",
            progressPercent: 100.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1565768770",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21005,
              courseName: "AP Calc AB",
              sectionID: 71392,
              taskID: 2,
              termID: 512,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 3,
              cumulativeTermName: "Q3",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              scoreID: 1076675,
              progressScore: "A",
              progressPercent: 100.0,
              progressPointsEarned: 40.0,
              progressTotalPoints: 40.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "-83366383",
              termName: "Q4",
              termSeq: 4,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 512,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 1076675,
            progressScore: "A",
            progressPercent: 100.0,
            progressPointsEarned: 40.0,
            progressTotalPoints: 40.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-83366383",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [],
              progress: {
                progressID: 616192,
                scoreID: 1076675,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 40.0,
                progressTotalPoints: 40.0,
                termID: 512,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "674954377",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
      ],
    },
  ];

  var temp: any = [];
  var terms = [];

  const [quarter, setQuarter] = useState("");
  const [assgns, setAssgns] = useState<GridRowModel[]>(temp);
  const [grade, setGrade] = useState("");
  const [categories, setCategories]: any = useState([]);

  for (var tasks = 0; tasks < data[0].details.length; tasks++) {
    const termName =
      data[0].details[tasks].task.termName +
      " " +
      data[0].details[tasks].task.taskName;
    terms.push(termName);
  }

  function getAssgns(quarter: any) {
    const ans = [];
    let cumTermName;
    if (data[0].details[quarter].task.cumulativeTermName) {
      cumTermName = data[0].details[quarter].task.cumulativeTermName;
      for (var i = 0; i < data[0].details.length; i++) {
        const groups = data[0].details[i].categories;
        if (groups.length > 0) {
          const term = data[0].details[i];
          if (
            term.task.termName == cumTermName ||
            term.task.cumulativeTermName == cumTermName
          ) {
            for (var j = 0; j < groups.length; j++) {
              var asgn = groups[j].assignments;
              for (var z = 0; z < asgn.length; z++) {
                var d = new Date(asgn[z].dueDate.split("T")[0]);
                if (asgn[z].score != null) {
                  ans.push({
                    category: groups[j].name,
                    id: asgn[z].assignmentName,
                    date: d,
                    points: Number(asgn[z].score),
                    total: asgn[z].totalPoints,
                  });
                }
              }
            }
          }
        }
      }
    } else {
      const groups = data[0].details[quarter].categories;
      if (groups.length > 0) {
        for (var i = 0; i < groups.length; i++) {
          var asgn = groups[i].assignments;
          for (var z = 0; z < asgn.length; z++) {
            var d = new Date(asgn[z].dueDate.split("T")[0]);
            if (asgn[z].score != null) {
              ans.push({
                category: groups[i].name,
                id: asgn[z].assignmentName,
                date: d,
                points: Number(asgn[z].score),
                total: asgn[z].totalPoints,
              });
            }
          }
        }
      }
    }

    return ans;
  }
  const [sortModel, setSortModel] = useState<GridSortModel>([
    {
      field: "date",
      sort: "desc",
    },
  ]);
  const [weighted, setWeighted] = useState(false);
  const [form, setForm] = useState({
    category: "",
    name: "",
    points: "",
    total: "",
  });

  useEffect(() => {
    calcGrade(assgns);
  }, [assgns]);

  const handleChange = (event: SelectChangeEvent) => {
    console.log(event);
    const q = Number(event.target.value);
    setQuarter(event.target.value as string);
    setAssgns(getAssgns(q));

    const cats: any = data[0].details[q].categories.map((a) => {
      return { name: a.name, weight: a.weight, num: 0, den: 0 };
    });
    setCategories(cats);

    var w = data[0].details[q].task.groupWeighted;
    setWeighted(w);
  };

  const change = (e: any) => {
    const value = e.target.value;
    setForm({
      ...form,
      [e.target.name]: value,
    });
  };

  const c: GridColDef[] = [
    { field: "id", headerName: "Name", width: 400 },
    { field: "category", headerName: "Category", width: 200 },

    { field: "date", headerName: "Due Date", type: "date", width: 400 },

    {
      field: "points",
      headerName: "Points",
      width: 400,
      editable: true,
      type: "number",
    },
    {
      field: "total",
      headerName: "Total",
      width: 400,
      editable: true,
      type: "number",
    },
    {
      field: "delete",
      headerName: "Delete",
      renderCell: () => (
        <strong>
          <Button variant="contained" size="small" style={{ marginLeft: 16 }}>
            Delete
          </Button>
        </strong>
      ),
    },
  ];

  function calcGrade(grades: any) {
    if (!weighted) {
      // console.log("not weighted");
      let total = 0;
      let points = 0;
      for (let value of grades) {
        points += value.points;
        total += value.total;
      }
      setGrade(((points / total) * 100).toFixed(2));
    } else {
      console.log("its weighted");
      let total = 0;
      let totalWeight = 0;

      for (let c of categories) {
        for (let a of grades) {
          if (a.category == c.name) {
            c.num += a.points;
            c.den += a.total;
          }
        }
      }
      for (let c of categories) {
        if (c.den != 0) {
          total += (c.num / c.den) * c.weight;
          totalWeight += c.weight;
        }
      }
      console.log(total);
      setGrade(((total / totalWeight) * 100).toFixed(2));
    }
  }
  const handleCommit = (e: GridCellEditCommitParams) => {
    const array = assgns.map((r) => {
      if (r.id === e.id) {
        return { ...r, [e.field]: e.value };
      } else {
        return { ...r };
      }
    });
    setAssgns(array);
  };

  const handleAddRow = (row: any) => {
    setAssgns((prevRows) => [
      ...prevRows,
      {
        id: row.name,
        category: row.category,
        date: new Date(),
        points: Number(row.points),
        total: Number(row.total),
      },
    ]);
    setForm({
      category: "",
      name: "",
      points: "",
      total: "",
    });
  };
  function test() {
    for (var i = 0; i < data[0].details.length; i++) {
      const task = data[0].details[i].children;
      console.log(i, task);
    }
  }

  //for delete only
  const handleCellClick = (params: GridCellParams) => {
    const value = params.colDef.field;

    if (!(value === "delete")) {
      return;
    }
    setAssgns((prevRows) => prevRows.filter((row) => row.id !== params.id));
  };

  return (
    <div className="App">
      <h2>Human Geo</h2>
      <InputLabel id="demo-simple-select-label">Quarter</InputLabel>

      <Box sx={{ minWidth: 120 }}>
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">Quarter</InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={quarter}
            label="Quarter"
            onChange={handleChange}
          >
            {terms.map((term, i) => (
              <MenuItem value={i}>{term}</MenuItem>
            ))}
          </Select>
        </FormControl>
      </Box>

      <h3>Add Assignment</h3>
      <Box
        component="form"
        sx={{
          "& > :not(style)": { m: 1, width: "25ch" },
        }}
        noValidate
        autoComplete="off"
      >
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">Category</InputLabel>
          <Select
            label="Category"
            onChange={change}
            name="category"
            value={form.category}
          >
            {categories.map((term: any) => (
              <MenuItem value={term}>{term}</MenuItem>
            ))}
          </Select>
        </FormControl>
        <TextField
          label="Name"
          onChange={change}
          name="name"
          value={form.name}
          variant="standard"
        />
        <TextField
          label="Points"
          onChange={change}
          name="points"
          type="number"
          value={form.points}
          variant="standard"
        />
        <TextField
          label="Total"
          type="number"
          name="total"
          onChange={change}
          value={form.total}
          variant="standard"
        />
        <Button onClick={() => handleAddRow(form)}>Add</Button>
      </Box>

      {/* <Button onClick={test}>Add</Button> */}

      <Button onClick={test}>test</Button>

      <h4>Grade: {grade}</h4>

      <div style={{ height: 900, width: "100%" }}>
        <DataGrid
          sortModel={sortModel}
          onSortModelChange={(model) => setSortModel(model)}
          onCellEditCommit={handleCommit}
          rows={assgns}
          columns={c}
          onCellClick={handleCellClick}
        />
      </div>

      <PointsBased />
    </div>
  );
}

export default Courses;
