import React, { useState, useEffect } from "react";
import "./App.css";
import {
  LineChart,
  Line,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
} from "recharts";

function Test() {
  const calcData = [
    {
      terms: [
        {
          termID: 509,
          termName: "Q1",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 1,
          isPrimary: true,
          startDate: "2021-08-18",
          endDate: "2021-10-15",
        },
        {
          termID: 510,
          termName: "Q2",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 2,
          isPrimary: true,
          startDate: "2021-10-18",
          endDate: "2021-12-22",
        },
        {
          termID: 511,
          termName: "Q3",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 3,
          isPrimary: true,
          startDate: "2022-01-10",
          endDate: "2022-03-17",
        },
        {
          termID: 512,
          termName: "Q4",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 4,
          isPrimary: true,
          startDate: "2022-03-21",
          endDate: "2022-06-06",
        },
      ],
      details: [
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 509,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 740350,
            score: "A-",
            percent: 92.8,
            progressScore: "A",
            progressPercent: 93.7,
            progressPointsEarned: 321.0,
            progressTotalPoints: 330.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1075816885",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 80153,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79353,
                  termID: 509,
                  assignmentName: "3.11",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-16T06:59:00.000Z",
                  assignedDate: "2021-10-14T07:00:00.000Z",
                  modifiedDate: "2021-10-21T22:43:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 59109,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 58415,
                  termID: 509,
                  assignmentName: "Implicit Differentiation Worksheet",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-08T06:59:00.000Z",
                  assignedDate: "2021-10-06T07:00:00.000Z",
                  modifiedDate: "2021-10-14T19:34:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 57549,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 56866,
                  termID: 509,
                  assignmentName: "3.10",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-06T06:59:00.000Z",
                  assignedDate: "2021-10-05T07:00:00.000Z",
                  modifiedDate: "2021-10-14T18:37:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 55807,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 55189,
                  termID: 509,
                  assignmentName: "3.9",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-09-29T07:00:00.000Z",
                  modifiedDate: "2021-10-14T18:37:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 48390,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 47853,
                  termID: 509,
                  assignmentName: "3.7",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-30T06:59:00.000Z",
                  assignedDate: "2021-09-27T07:00:00.000Z",
                  modifiedDate: "2021-10-04T16:24:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 51524,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 50948,
                  termID: 509,
                  assignmentName: "3.8",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-30T06:59:00.000Z",
                  assignedDate: "2021-09-29T07:00:00.000Z",
                  modifiedDate: "2021-10-04T21:35:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 44469,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 43951,
                  termID: 509,
                  assignmentName: "3.6",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-25T06:59:00.000Z",
                  assignedDate: "2021-09-24T07:00:00.000Z",
                  modifiedDate: "2021-09-28T15:57:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 44464,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 43946,
                  termID: 509,
                  assignmentName: "3.5",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-24T06:59:00.000Z",
                  assignedDate: "2021-09-23T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37229,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36743,
                  termID: 509,
                  assignmentName: "3.4",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-21T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37217,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36731,
                  termID: 509,
                  assignmentName: "3.1",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-19T21:29:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37223,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36737,
                  termID: 509,
                  assignmentName: "3.1/3.2 Extra Practice",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37220,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36734,
                  termID: 509,
                  assignmentName: "3.2",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 37226,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 36740,
                  termID: 509,
                  assignmentName: "3.3",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-20T06:59:00.000Z",
                  assignedDate: "2021-09-19T07:00:00.000Z",
                  modifiedDate: "2021-09-23T22:23:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 26378,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 25946,
                  termID: 509,
                  assignmentName: "Ch 1&2 HW",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-11T06:59:00.000Z",
                  assignedDate: "2021-09-10T07:00:00.000Z",
                  modifiedDate: "2021-09-11T01:01:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "100",
                  scorePoints: "100.0",
                  scorePercentage: "100.0",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244945,
                scoreID: 740350,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 230.0,
                progressTotalPoints: 230.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 13844,
              name: "Tests/Projects/Finals",
              weight: 70.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 26382,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 25950,
                  termID: 509,
                  assignmentName: "Ch 2 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-09-11T06:59:00.000Z",
                  assignedDate: "2021-09-10T07:00:00.000Z",
                  modifiedDate: "2021-09-21T01:33:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "91",
                  scorePoints: "91.0",
                  scorePercentage: "91.0",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244946,
                scoreID: 740350,
                groupID: 13844,
                progressScore: "A-",
                progressPercent: 91.0,
                progressTrendVal: null,
                progressPointsEarned: 91.0,
                progressTotalPoints: 100.0,
                termID: 509,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 509,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 849964,
            score: "A",
            percent: 96.53,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "272236671",
            termName: "Q1",
            termSeq: 1,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 1,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 740352,
            progressScore: "A-",
            progressPercent: 92.47,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "1460943609",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21005,
              courseName: "AP Calc AB",
              sectionID: 71392,
              taskID: 2,
              termID: 510,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 1,
              cumulativeTermName: "Q1",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              scoreID: 740351,
              progressScore: "A-",
              progressPercent: 92.47,
              progressPointsEarned: 468.5,
              progressTotalPoints: 490.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "709819788",
              termName: "Q2",
              termSeq: 2,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 510,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 740351,
            progressScore: "A-",
            progressPercent: 92.47,
            progressPointsEarned: 468.5,
            progressTotalPoints: 490.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "709819788",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [
            {
              groupID: 16688,
              name: "Assessments",
              weight: 70.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 123342,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 122289,
                  termID: 510,
                  assignmentName: "Cheat Sheet Extra Credit",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-12-07T07:59:00.000Z",
                  assignedDate: "2021-12-03T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: null,
            },
            {
              groupID: 13841,
              name: "HW",
              weight: 30.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 119612,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 118562,
                  termID: 510,
                  assignmentName: "5.1",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-12-07T07:59:00.000Z",
                  assignedDate: "2021-11-30T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 110937,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 109951,
                  termID: 510,
                  assignmentName: "4.9",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-19T07:59:00.000Z",
                  assignedDate: "2021-11-17T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 108442,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 107461,
                  termID: 510,
                  assignmentName: "4.7",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-18T07:59:00.000Z",
                  assignedDate: "2021-11-15T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 108436,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 107455,
                  termID: 510,
                  assignmentName: "4.6",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-17T07:59:00.000Z",
                  assignedDate: "2021-11-12T08:00:00.000Z",
                  modifiedDate: "2021-11-19T17:13:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 101308,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 100380,
                  termID: 510,
                  assignmentName: "4.5 ",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-12T07:59:00.000Z",
                  assignedDate: "2021-11-09T08:00:00.000Z",
                  modifiedDate: "2021-11-17T20:28:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 100604,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 99680,
                  termID: 510,
                  assignmentName: "4.4",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-09T07:59:00.000Z",
                  assignedDate: "2021-11-08T08:00:00.000Z",
                  modifiedDate: "2021-11-17T20:26:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 84135,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 83312,
                  termID: 510,
                  assignmentName: "4.3 ",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-29T06:59:00.000Z",
                  assignedDate: "2021-10-25T07:00:00.000Z",
                  modifiedDate: "2021-11-17T20:22:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 80107,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79307,
                  termID: 510,
                  assignmentName: "4.2",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-22T06:59:00.000Z",
                  assignedDate: "2021-10-21T07:00:00.000Z",
                  modifiedDate: "2021-10-22T19:13:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 80318,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 79518,
                  termID: 510,
                  assignmentName: "4.1",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-10-20T06:59:00.000Z",
                  assignedDate: "2021-10-18T07:00:00.000Z",
                  modifiedDate: "2021-10-22T19:13:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244947,
                scoreID: 740351,
                groupID: 13841,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 290.0,
                progressTotalPoints: 290.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 13844,
              name: "Tests/Projects/Finals",
              weight: 70.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 100661,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 11295,
                  taskID: 2,
                  groupActivityID: 99737,
                  termID: 510,
                  assignmentName: "Ch 3 Test",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71392,
                  courseID: 21005,
                  dueDate: "2021-11-09T07:59:00.000Z",
                  assignedDate: "2021-11-08T08:00:00.000Z",
                  modifiedDate: "2021-11-09T04:28:00.000Z",
                  courseName: "AP Calc AB",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "87.5",
                  scorePoints: "87.5",
                  scorePercentage: "87.5",
                  totalPoints: 100,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 244948,
                scoreID: 740351,
                groupID: 13844,
                progressScore: "B+",
                progressPercent: 89.25,
                progressTrendVal: null,
                progressPointsEarned: 178.5,
                progressTotalPoints: 200.0,
                termID: 510,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 988036,
            score: "A-",
            percent: 92.47,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-610888853",
            termName: "Q2",
            termSeq: 2,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-92665522",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1542803576",
            termName: "Q3",
            termSeq: 3,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 1,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1733069597",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: [
            {
              _id: "11295",
              personID: 11295,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 21005,
              courseName: "AP Calc AB",
              sectionID: 71392,
              taskID: 2,
              termID: 512,
              hasAssignments: false,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 3,
              cumulativeTermName: "Q3",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: false,
              _model: "PortalGradingTaskModel",
              _hashCode: "2125092431",
              termName: "Q4",
              termSeq: 4,
            },
          ],
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 2,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "2125092431",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "11295",
            personID: 11295,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 21005,
            courseName: "AP Calc AB",
            sectionID: 71392,
            taskID: 3,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "674954377",
            termName: "Q4",
            termSeq: 4,
          },
          categories: [],
          children: null,
        },
      ],
    },
  ];
  var dates = [];
  var cats: any = [];
  console.log(cats);

  //   for (var tasks = 0; tasks < calcData[0].details.length; tasks++) {
  //   const groups = calcData[0].details[tasks].categories;
  const groups = calcData[0].details[0].categories;

  if (groups.length > 0) {
    for (var i = 0; i < groups.length; i++) {
      cats.push({ num: 0, den: 0, weight: groups[i].weight / 100 });

      var asgn = groups[i].assignments;

      for (var z = 0; z < asgn.length; z++) {
        var d = new Date(asgn[z].dueDate.split("T")[0]);
        if (asgn[z].score != null) {
          dates.push({
            index: i,
            date: d,
            total: asgn[z].totalPoints,
            score: Number(asgn[z].score),
            asgn: asgn[z].assignmentName,
          });
        }
      }
    }
  }
  dates.sort(function (a, b) {
    return +new Date(a.date) - +new Date(b.date);
  });
  console.log(dates);

  //Given an assignment, adds to respective category and calculates grade. Cats is updated
  function calcGrade(index: number, num: number, den: number) {
    let total = 0;
    let totalWeight = 0;
    cats[index].num += num;
    cats[index].den += den;
    console.log(cats);
    for (var i = 0; i < cats.length; i++) {
      total += (cats[i].num / cats[i].den) * cats[i].weight;
      totalWeight += cats[i].weight;
    }

    return total / totalWeight;
  }

  const calc = [];

  for (var i = 0; i < dates.length; i++) {
    // console.log("iteration: " + i);

    var grade = calcGrade(dates[i].index, dates[i].score, dates[i].total);
    console.log(dates[i].asgn + ": " + grade.toFixed(1));

    calc.push({
      date: dates[i].date.toLocaleDateString(),
      grade: grade.toFixed(2),
      name: " s" + dates[i].asgn,
    });
  }

  return (
    <div className="App">
      <LineChart width={600} height={300} data={calc}>
        <Line type="monotone" dataKey="grade" stroke="#8884d8" />
        <Line type="monotone" dataKey="name" stroke="#8884d8" />
        <CartesianGrid stroke="#ccc" />
        <XAxis dataKey="date" />
        <YAxis />
        <Tooltip />
      </LineChart>
    </div>
  );
}

export default Test;
