import React, { useState, useEffect } from "react";
import "./App.css";
import {
  LineChart,
  Line,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
} from "recharts";

function WeightedGrade() {
  //71392?showAllTerms=false
  //details, terms
  const calcData = [
    {
      terms: [
        {
          termID: 509,
          termName: "Q1",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 1,
          isPrimary: true,
          startDate: "2021-08-18",
          endDate: "2021-10-15",
        },
        {
          termID: 510,
          termName: "Q2",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 2,
          isPrimary: true,
          startDate: "2021-10-18",
          endDate: "2021-12-22",
        },
        {
          termID: 511,
          termName: "Q3",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 3,
          isPrimary: true,
          startDate: "2022-01-10",
          endDate: "2022-03-17",
        },
        {
          termID: 512,
          termName: "Q4",
          termScheduleID: 181,
          termScheduleName: "Quarters",
          termSeq: 4,
          isPrimary: true,
          startDate: "2022-03-21",
          endDate: "2022-06-06",
        },
      ],
      details: [
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 2,
            termID: 509,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 762400,
            score: "A-",
            percent: 91.52,
            progressScore: "B+",
            progressPercent: 87.61,
            progressPointsEarned: 108.0,
            progressTotalPoints: 118.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "1867120453",
            termSeq: 1,
            termName: "Q1",
          },
          categories: [
            {
              groupID: 8024,
              name: "classwork",
              weight: 20.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 68142,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67399,
                  termID: 509,
                  assignmentName: "9/10",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T17:27:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68722,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67966,
                  termID: 509,
                  assignmentName: "calcMethod",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T21:25:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68068,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67325,
                  termID: 509,
                  assignmentName: "Division without division",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T17:04:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68459,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67712,
                  termID: 509,
                  assignmentName: "Even Stevens",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T19:17:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68602,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67853,
                  termID: 509,
                  assignmentName: "Evil 6's",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T20:42:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68210,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67467,
                  termID: 509,
                  assignmentName: "Lance's Tre's",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T18:50:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 68005,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 67262,
                  termID: 509,
                  assignmentName: "LCM",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-14T06:59:00.000Z",
                  assignedDate: "2021-10-13T07:00:00.000Z",
                  modifiedDate: "2021-10-13T16:27:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 57486,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 56803,
                  termID: 509,
                  assignmentName: "isPrime",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-06T06:59:00.000Z",
                  assignedDate: "2021-10-05T07:00:00.000Z",
                  modifiedDate: "2021-10-05T15:20:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 39937,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 39448,
                  termID: 509,
                  assignmentName: "calcMethod",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-09-22T06:59:00.000Z",
                  assignedDate: "2021-09-21T07:00:00.000Z",
                  modifiedDate: "2021-09-21T16:46:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 40406,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 39902,
                  termID: 509,
                  assignmentName: "conversion/truth table",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-09-22T06:59:00.000Z",
                  assignedDate: "2021-09-21T07:00:00.000Z",
                  modifiedDate: "2021-09-21T19:08:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 34830,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 34399,
                  termID: 509,
                  assignmentName: "in class check off 1 and 2",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-09-17T06:59:00.000Z",
                  assignedDate: "2021-09-16T07:00:00.000Z",
                  modifiedDate: "2021-09-17T18:56:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 272617,
                scoreID: 762400,
                groupID: 8024,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 60.0,
                progressTotalPoints: 60.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 7810,
              name: "projects",
              weight: 25.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 70608,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 69833,
                  termID: 509,
                  assignmentName: "FryLau",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-15T06:59:00.000Z",
                  assignedDate: "2021-10-14T07:00:00.000Z",
                  modifiedDate: "2021-10-15T05:13:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 35534,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 35051,
                  termID: 509,
                  assignmentName: "Tic Tac Toe",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-09-18T06:59:00.000Z",
                  assignedDate: "2021-09-17T07:00:00.000Z",
                  modifiedDate: "2021-10-04T16:42:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 30310,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 29909,
                  termID: 509,
                  assignmentName: "MadLibs",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-09-15T06:59:00.000Z",
                  assignedDate: "2021-09-14T07:00:00.000Z",
                  modifiedDate: "2021-09-14T15:51:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 272616,
                scoreID: 762400,
                groupID: 7810,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 20.0,
                progressTotalPoints: 20.0,
                termID: 509,
                taskID: 2,
              },
            },
            {
              groupID: 7988,
              name: "tests",
              weight: 40.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 55996,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 55345,
                  termID: 509,
                  assignmentName: "Test1",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-05T06:59:00.000Z",
                  assignedDate: "2021-10-04T07:00:00.000Z",
                  modifiedDate: "2021-10-07T18:59:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "28",
                  scorePoints: "28.0",
                  scorePercentage: "73.684",
                  totalPoints: 38,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 413642,
                scoreID: 762400,
                groupID: 7988,
                progressScore: "C",
                progressPercent: 73.68,
                progressTrendVal: null,
                progressPointsEarned: 28.0,
                progressTotalPoints: 38.0,
                termID: 509,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 3,
            termID: 509,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1024858072",
            termSeq: 1,
            termName: "Q1",
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 1,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            scoreID: 762402,
            progressScore: "B-",
            progressPercent: 81.91,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-409337668",
            termSeq: 2,
            termName: "Q2",
          },
          categories: [],
          children: [
            {
              _id: "23177",
              personID: 23177,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 20591,
              courseName: "AP Comp Sci A",
              sectionID: 71161,
              taskID: 2,
              termID: 510,
              hasAssignments: true,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 1,
              cumulativeTermName: "Q1",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              scoreID: 762401,
              progressScore: "B-",
              progressPercent: 81.91,
              progressPointsEarned: 284.0,
              progressTotalPoints: 335.0,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: true,
              _model: "PortalGradingTaskModel",
              _hashCode: "-1523186865",
              termSeq: 2,
              termName: "Q2",
            },
          ],
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 2,
            termID: 510,
            hasAssignments: true,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 1,
            cumulativeTermName: "Q1",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            scoreID: 762401,
            progressScore: "B-",
            progressPercent: 81.91,
            progressPointsEarned: 284.0,
            progressTotalPoints: 335.0,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1523186865",
            termSeq: 2,
            termName: "Q2",
          },
          categories: [
            {
              groupID: 8024,
              name: "classwork",
              weight: 20.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 144174,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 143085,
                  termID: 510,
                  assignmentName: "partner inheritance",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-23T07:59:00.000Z",
                  assignedDate: "2021-12-22T08:00:00.000Z",
                  modifiedDate: "2021-12-22T16:58:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 143867,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 142777,
                  termID: 510,
                  assignmentName: "array and object practice ",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-22T07:59:00.000Z",
                  assignedDate: "2021-12-21T08:00:00.000Z",
                  modifiedDate: "2021-12-22T03:45:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 143857,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 142767,
                  termID: 510,
                  assignmentName: "rectangle object",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-22T07:59:00.000Z",
                  assignedDate: "2021-12-21T08:00:00.000Z",
                  modifiedDate: "2021-12-22T03:41:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 143850,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 142760,
                  termID: 510,
                  assignmentName: "shoe sock",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-22T07:59:00.000Z",
                  assignedDate: "2021-12-21T08:00:00.000Z",
                  modifiedDate: "2021-12-22T03:38:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 138013,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 136928,
                  termID: 510,
                  assignmentName: "Fractions Object",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-17T07:59:00.000Z",
                  assignedDate: "2021-12-16T08:00:00.000Z",
                  modifiedDate: "2021-12-16T17:38:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 136428,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 135347,
                  termID: 510,
                  assignmentName: "object turnin",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-15T07:59:00.000Z",
                  assignedDate: "2021-12-14T08:00:00.000Z",
                  modifiedDate: "2021-12-15T05:02:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 135031,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 133950,
                  termID: 510,
                  assignmentName: "object turn in",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-14T07:59:00.000Z",
                  assignedDate: "2021-12-13T08:00:00.000Z",
                  modifiedDate: "2021-12-14T03:58:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 135018,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 133937,
                  termID: 510,
                  assignmentName: "string commands are fun",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-14T07:59:00.000Z",
                  assignedDate: "2021-12-13T08:00:00.000Z",
                  modifiedDate: "2021-12-14T03:48:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 121028,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 119976,
                  termID: 510,
                  assignmentName: "random worksheet",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-02T07:59:00.000Z",
                  assignedDate: "2021-12-01T08:00:00.000Z",
                  modifiedDate: "2021-12-01T23:18:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 119447,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 118398,
                  termID: 510,
                  assignmentName: "ArrayFractions",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-01T07:59:00.000Z",
                  assignedDate: "2021-11-30T08:00:00.000Z",
                  modifiedDate: "2021-11-30T21:48:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 118583,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 117548,
                  termID: 510,
                  assignmentName: "arraySorter",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-11-30T07:59:00.000Z",
                  assignedDate: "2021-11-29T08:00:00.000Z",
                  modifiedDate: "2021-11-29T23:28:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 83638,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 82815,
                  termID: 510,
                  assignmentName: "bigBirdsNest",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-10-25T06:59:00.000Z",
                  assignedDate: "2021-10-24T07:00:00.000Z",
                  modifiedDate: "2021-10-25T04:03:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "5",
                  scorePoints: "5.0",
                  scorePercentage: "100.0",
                  totalPoints: 5,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 272619,
                scoreID: 762401,
                groupID: 8024,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 120.0,
                progressTotalPoints: 120.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 7921,
              name: "final",
              weight: 15.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 141897,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 140811,
                  termID: 510,
                  assignmentName: "final",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-21T07:59:00.000Z",
                  assignedDate: "2021-12-20T08:00:00.000Z",
                  modifiedDate: "2021-12-21T21:11:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "28",
                  scorePoints: "28.0",
                  scorePercentage: "65.116",
                  totalPoints: 43,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 536283,
                scoreID: 762401,
                groupID: 7921,
                progressScore: "D",
                progressPercent: 65.11,
                progressTrendVal: null,
                progressPointsEarned: 28.0,
                progressTotalPoints: 43.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 7810,
              name: "projects",
              weight: 25.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 144336,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 143247,
                  termID: 510,
                  assignmentName: "bubblesort",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-23T07:59:00.000Z",
                  assignedDate: "2021-12-22T08:00:00.000Z",
                  modifiedDate: "2021-12-22T19:34:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 144200,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 143111,
                  termID: 510,
                  assignmentName: "Checkers",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-23T07:59:00.000Z",
                  assignedDate: "2021-12-22T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 50,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 144095,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 143006,
                  termID: 510,
                  assignmentName: "connect4",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-23T07:59:00.000Z",
                  assignedDate: "2021-12-22T08:00:00.000Z",
                  modifiedDate: "2021-12-22T16:49:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 144345,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 143256,
                  termID: 510,
                  assignmentName: "RoadRace",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-23T07:59:00.000Z",
                  assignedDate: "2021-12-22T08:00:00.000Z",
                  modifiedDate: null,
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: null,
                  scorePoints: null,
                  scorePercentage: null,
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: null,
                  missing: null,
                  cheated: null,
                  dropped: null,
                  incomplete: null,
                  turnedIn: null,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 143841,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 142751,
                  termID: 510,
                  assignmentName: "smart arrays",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-22T07:59:00.000Z",
                  assignedDate: "2021-12-21T08:00:00.000Z",
                  modifiedDate: "2021-12-22T03:35:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 135029,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 133948,
                  termID: 510,
                  assignmentName: "pascal's triangle",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-14T07:59:00.000Z",
                  assignedDate: "2021-12-13T08:00:00.000Z",
                  modifiedDate: "2021-12-14T03:55:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "10",
                  scorePoints: "10.0",
                  scorePercentage: "100.0",
                  totalPoints: 10,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 272618,
                scoreID: 762401,
                groupID: 7810,
                progressScore: "A",
                progressPercent: 100.0,
                progressTrendVal: null,
                progressPointsEarned: 60.0,
                progressTotalPoints: 60.0,
                termID: 510,
                taskID: 2,
              },
            },
            {
              groupID: 7988,
              name: "tests",
              weight: 40.0,
              seq: 0,
              isExcluded: false,
              isWeighted: true,
              usePercent: false,
              assignments: [
                {
                  objectSectionID: 137516,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 136435,
                  termID: 510,
                  assignmentName: "Test 3 ",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-12-16T07:59:00.000Z",
                  assignedDate: "2021-12-15T08:00:00.000Z",
                  modifiedDate: "2021-12-19T00:09:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "22",
                  scorePoints: "22.0",
                  scorePercentage: "57.895",
                  totalPoints: 38,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
                {
                  objectSectionID: 96843,
                  parentObjectSectionID: null,
                  type: 7,
                  personID: 23177,
                  taskID: 2,
                  groupActivityID: 95943,
                  termID: 510,
                  assignmentName: "Test 2",
                  schoolID: 13,
                  calendarID: 646,
                  structureID: 646,
                  sectionID: 71161,
                  courseID: 20591,
                  dueDate: "2021-11-06T06:59:00.000Z",
                  assignedDate: "2021-11-05T07:00:00.000Z",
                  modifiedDate: "2021-11-05T18:19:00.000Z",
                  courseName: "AP Comp Sci A",
                  hasMultipleScores: null,
                  active: true,
                  scoringType: "p",
                  score: "26",
                  scorePoints: "26.0",
                  scorePercentage: "72.222",
                  totalPoints: 36,
                  comments: null,
                  feedback: null,
                  late: false,
                  missing: false,
                  cheated: false,
                  dropped: false,
                  incomplete: false,
                  turnedIn: false,
                  wysiwygSubmission: false,
                  upload: false,
                  driveSubmission: false,
                  multiplier: 1.0,
                  hasStudentHTML: null,
                  hasTeacherHTML: null,
                  hasQuiz: null,
                  hasLTI: null,
                  hasLTIAcceptsScores: null,
                  hasFile: null,
                  hasExternalFile: null,
                  hasSubmission: null,
                  hasDiscussion: null,
                  hasRubric: null,
                  notGraded: false,
                  includeCampusLearning: true,
                },
              ],
              progress: {
                progressID: 413643,
                scoreID: 762401,
                groupID: 7988,
                progressScore: "D+",
                progressPercent: 67.85,
                progressTrendVal: null,
                progressPointsEarned: 76.0,
                progressTotalPoints: 112.0,
                termID: 510,
                taskID: 2,
              },
            },
          ],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 3,
            termID: 510,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            scoreID: 951750,
            score: "B+",
            percent: 87.28,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-12649168",
            termSeq: 2,
            termName: "Q2",
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 2,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1865017001",
            termSeq: 3,
            termName: "Q3",
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 3,
            termID: 511,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-884309462",
            termSeq: 3,
            termName: "Q3",
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 1,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: true,
            taskName: "Semester Final",
            gradedOnce: false,
            treeTraversalSeq: 1,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: false,
            usePercent: false,
            curveID: 6,
            hasDetail: true,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1074402497",
            termSeq: 4,
            termName: "Q4",
          },
          categories: [],
          children: [
            {
              _id: "23177",
              personID: 23177,
              trialID: 773,
              calendarID: 646,
              structureID: 646,
              courseID: 20591,
              courseName: "AP Comp Sci A",
              sectionID: 71161,
              taskID: 2,
              termID: 512,
              hasAssignments: false,
              hasCompositeTasks: false,
              taskName: "Quarter Grade",
              gradedOnce: false,
              treeTraversalSeq: 2,
              cumulativeTermSeq: 3,
              cumulativeTermName: "Q3",
              maxAssignments: 0,
              calcMethod: "nu",
              groupWeighted: true,
              usePercent: false,
              curveID: 6,
              calculationWeight: 100.0,
              calculationPercent: 1.0,
              hasDetail: false,
              _model: "PortalGradingTaskModel",
              _hashCode: "-1511207765",
              termSeq: 4,
              termName: "Q4",
            },
          ],
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 2,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Quarter Grade",
            gradedOnce: false,
            treeTraversalSeq: 2,
            cumulativeTermSeq: 3,
            cumulativeTermName: "Q3",
            maxAssignments: 0,
            calcMethod: "nu",
            groupWeighted: true,
            usePercent: false,
            curveID: 6,
            calculationWeight: 100.0,
            calculationPercent: 1.0,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "-1511207765",
            termSeq: 4,
            termName: "Q4",
          },
          categories: [],
          children: null,
        },
        {
          task: {
            _id: "23177",
            personID: 23177,
            trialID: 773,
            calendarID: 646,
            structureID: 646,
            courseID: 20591,
            courseName: "AP Comp Sci A",
            sectionID: 71161,
            taskID: 3,
            termID: 512,
            hasAssignments: false,
            hasCompositeTasks: false,
            taskName: "Mid-Term Grade",
            gradedOnce: false,
            treeTraversalSeq: 3,
            cumulativeTermSeq: 0,
            maxAssignments: 0,
            calcMethod: "no",
            groupWeighted: false,
            usePercent: false,
            hasDetail: false,
            _model: "PortalGradingTaskModel",
            _hashCode: "1333448491",
            termSeq: 4,
            termName: "Q4",
          },
          categories: [],
          children: null,
        },
      ],
    },
  ];
  var dates = [];
  var cats: any = [];
  console.log(cats);

  //   for (var tasks = 0; tasks < calcData[0].details.length; tasks++) {
  //   const groups = calcData[0].details[tasks].categories;
  const groups = calcData[0].details[0].categories;

  if (groups.length > 0) {
    for (var i = 0; i < groups.length; i++) {
      cats.push({ num: 0, den: 0, weight: groups[i].weight / 100 });

      var asgn = groups[i].assignments;

      for (var z = 0; z < asgn.length; z++) {
        var d = new Date(asgn[z].dueDate.split("T")[0]);
        if (asgn[z].score != null) {
          dates.push({
            index: i,
            date: d,
            total: asgn[z].totalPoints,
            score: Number(asgn[z].score),
            asgn: asgn[z].assignmentName,
          });
        }
      }
    }
  }
  dates.sort(function (a, b) {
    return +new Date(a.date) - +new Date(b.date);
  });
  console.log("dates: ", dates);

  //Given an assignment, adds to respective category and calculates grade. Cats is updated
  function calcGrade(index: number, num: number, den: number) {
    let total = 0;
    let totalWeight = 0;
    cats[index].num += num;
    cats[index].den += den;
    for (var i = 0; i < cats.length; i++) {
      if (cats[i].den != 0) {
        total += (cats[i].num / cats[i].den) * cats[i].weight;
        totalWeight += cats[i].weight;
      }
    }
    return total / totalWeight;
  }

  const calc = [];

  // var grade = calcGrade(0, 100, 100);
  // calc.push({
  //   date: "1/1/1",
  //   grade: grade,
  //   name: "ch 1 and 2 hw",
  // });

  // var grade1 = calcGrade(1, 91, 100);
  // calc.push({
  //   date: "1/2/1",
  //   grade: grade1,
  //   name: "ch 2 test",
  // });

  // var grade2 = calcGrade(0, 10, 10);
  // calc.push({
  //   date: "1/3/1",
  //   grade: grade2,
  //   name: "3.1",
  // });

  // var grade3 = calcGrade(0, 10, 10);
  // calc.push({
  //   date: "1/4/1",
  //   grade: grade3,
  //   name: "extra practice",
  // });

  for (var i = 0; i < dates.length; i++) {
    var grade = calcGrade(dates[i].index, dates[i].score, dates[i].total);
    calc.push({
      date: dates[i].date.toLocaleDateString(),
      grade: grade,
      name: " s" + dates[i].asgn,
    });
  }

  return (
    <div className="App">
      <LineChart width={600} height={300} data={calc}>
        <Line type="monotone" dataKey="grade" stroke="#8884d8" />
        <Line type="monotone" dataKey="name" stroke="#8884d8" />
        <CartesianGrid stroke="#ccc" />
        <XAxis dataKey="date" />
        <YAxis />
        <Tooltip />
      </LineChart>
    </div>
  );
}

export default WeightedGrade;
